name: caltrack
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  image_picker: ^1.0.8
  google_maps_flutter: ^2.5.3
  flutter_gemini: ^2.0.5
  intl: ^0.19.0
  camera: ^0.11.0+1
  path_provider: ^2.1.4
  path: ^1.8.3
  permission_handler: ^11.3.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/maps.json
